import { Bill } from "src/features/income-tracker/Bill"
import { getRelativeTimeDate } from "src/lib/utils/getRelativeTime"

export const DUMMY_BILL_PREFIX_ID = "dummyBills"

export const dummyBills: Bill[] = [
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-10),
    customer: {
      adress: "10 rue Beauvais, 69293 Quimper",
      name: "Lecomte & Caron",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-1cfdf7e2-b198-11ec-b909-0242ac120002`,
    number: 12,
    ownerId: null,
    remindedAt: [getRelativeTimeDate(-2)],
    sentAt: getRelativeTimeDate(-9),
    services: [
      {
        detail: "Site web",
        id: "S9xl9rH36r5GyM0KdOLA_",
        price: 8726,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Site web",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-1),
    customer: {
      adress: "8 rue Quimper, 66340 Nîmes",
      name: "Click",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-218acee8-b198-11ec-b909-0242ac120002`,
    number: 1,
    ownerId: null,
    remindedAt: [],
    sentAt: getRelativeTimeDate(-1),
    services: [
      {
        detail: "Flyer",
        id: "2E3d-TsUZw-_RC0zx-CF0",
        price: 1234,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Flyer",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-8),
    customer: {
      adress: "23 rue Grenoble, 85046 Saint-Maur-des-Fossés",
      name: "Awesome Company",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-46be769c-b198-11ec-b909-0242ac120002`,
    number: 2,
    ownerId: null,
    remindedAt: [],
    sentAt: getRelativeTimeDate(-8),
    services: [
      {
        detail: "Landing Page",
        id: "kmAi7IhhuVF4CwTj2yyud",
        price: 2581.52,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Landing Page",
    isDummy: true,
  },
  {
    cashedAt: getRelativeTimeDate(-4),
    createdAt: getRelativeTimeDate(-12),
    customer: {
      adress: "35 rue Saint-Denis, 45872 Saint-Étienne",
      name: "Merge data",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-4e819b34-b198-11ec-b909-0242ac120002`,
    number: 3,
    ownerId: null,
    remindedAt: [],
    sentAt: getRelativeTimeDate(-8),
    services: [
      {
        detail: "Tunnel de vente",
        id: "6TqlnzSurjc1p4U9a7fn-",
        price: 9085.15,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Tunnel de vente",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-5),
    customer: {
      adress: "846 rue Champigny-sur-Marne, 86790 Beauvais",
      name: "Render View",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-54d09e4a-b198-11ec-b909-0242ac120002`,
    number: 4,
    ownerId: null,
    remindedAt: [],
    sentAt: null,
    services: [
      {
        detail: "Site web WordPress",
        id: "toYG4jiWy-d6VLt6uUtBz",
        price: 7801.59,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Site web WordPress",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-1),
    customer: {
      adress: "778 rue Toulon, 22503 Pessac",
      name: "Dual",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-5b8d4c56-b198-11ec-b909-0242ac120002`,
    number: 5,
    ownerId: null,
    remindedAt: [],
    sentAt: null,
    services: [
      {
        detail: "Web app",
        id: "C5l1PncSfG4TylrQyPjag",
        price: 6211,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Web app",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-10),
    customer: {
      adress: "07 rue Saint-Denis, 66386 Cergy",
      name: "Hackney",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-640ae6cc-b198-11ec-b909-0242ac120002`,
    number: 6,
    ownerId: null,
    remindedAt: [],
    sentAt: null,
    services: [
      {
        detail: "Template Blog",
        id: "_WSjQ0S32WZbZ4OZSg2Sz",
        price: 9085.55,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Template blog",
    isDummy: true,
  },
  {
    cashedAt: null,
    createdAt: getRelativeTimeDate(-15),
    customer: {
      adress: "5 rue Cergy, 66257 Champigny-sur-Marne",
      name: "Crossfit",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-8005dec2-b198-11ec-b909-0242ac120002`,
    number: 7,
    ownerId: null,
    remindedAt: [],
    sentAt: getRelativeTimeDate(-15),
    services: [
      {
        detail: "Illustration",
        id: "UgriwI2X6-JbN7DlIR6Ep",
        price: 1205.15,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Illustration",
    isDummy: true,
  },
  {
    cashedAt: getRelativeTimeDate(-20),
    createdAt: getRelativeTimeDate(-25),
    customer: {
      adress: "4 rue Sarcelles, 73259 Valence",
      name: "Ceding",
      siren: "123 456 789",
    },
    id: `${DUMMY_BILL_PREFIX_ID}-694e56a0-b198-11ec-b909-0242ac120002`,
    number: 8,
    ownerId: null,
    remindedAt: [],
    sentAt: getRelativeTimeDate(-20),
    services: [
      {
        detail: "Template Shopify",
        id: "zXs53O65Lal8jCHu_eViF",
        price: 12000,
        quantity: 1,
      },
    ],
    taxRate: 20,
    description: "Template Shopify",
    isDummy: true,
  },
]
