export enum FormData {
  userAccentColor = "userAccentColor",
  userBic = "userBic",
  userIban = "userIban",
  societyName = "societyName",
  userSocietyLogo = "userSocietyLogo",
  societyBaseline = "societyBaseline",
  societyAdress = "societyAdress",
  societyPhone = "societyPhone",
  societyEmail = "societyEmail",
  societySiren = "societySiren",
  customerName = "customerName",
  customerAdress = "customerAdress",
  customerSiren = "customerSiren",
  serviceDetails = "serviceDetails",
  serviceQuantity = "serviceQuantity",
  servicePrice = "servicePrice",
  billNumber = "billNumber",
}
