import { billProps } from "utils/types/billProps"
import time from "../helpers/dateHelpers"

export const getDateFromToday = (n: number): number =>
  time().subtract(n, "day").toDate().getTime()

const dummyBills: billProps[] = [
  {
    amount: 8726,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(20),
    customer: "Lecomte & Caron",
    description: "Magna cillum tempor nisi",
    id: "demo-1cfdf7e2-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [getDateFromToday(3)],
    sentAt: getDateFromToday(20),
    updatedAt: getDateFromToday(3),
  },
  {
    amount: 5169.52,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(12),
    customer: "Click",
    description: "Ipsum magna incididunt irure",
    id: "demo-218acee8-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: getDateFromToday(12),
    updatedAt: getDateFromToday(12),
  },
  {
    amount: 2581.52,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(3),
    customer: "Awesome Company",
    description: "Reprehenderit consequat sint aute velit",
    id: "demo-46be769c-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: getDateFromToday(3),
    updatedAt: getDateFromToday(3),
  },
  {
    amount: 9085.15,
    cashedAt: getDateFromToday(1),
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(30),
    customer: "Merge data",
    description: "Laborum Lorem veniam quis minim quis eu anim voluptate",
    id: "demo-4e819b34-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: getDateFromToday(30),
    updatedAt: getDateFromToday(1),
  },
  {
    amount: 7801.59,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(5),
    customer: "Render View",
    description: "Aliqua sint aliqua occaecat qui pariatur.",
    id: "demo-54d09e4a-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: null,
    updatedAt: getDateFromToday(5),
  },
  {
    amount: 6211,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(1),
    customer: "Dual",
    description: "Eu pariatur ullamco et aliquip.",
    id: "demo-5b8d4c56-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: null,
    updatedAt: getDateFromToday(1),
  },
  {
    amount: 9085.55,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(3),
    customer: "Hackney",
    description: "In dolor esse officia",
    id: "demo-640ae6cc-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: null,
    updatedAt: getDateFromToday(3),
  },
  {
    amount: 12005.15,
    cashedAt: null,
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(6),
    customer: "Crossfit",
    description: "Proident pariatur magna adipisicing aliquip",
    id: "demo-8005dec2-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: getDateFromToday(6),
    updatedAt: getDateFromToday(6),
  },
  {
    amount: 12000,
    cashedAt: getDateFromToday(15),
    cashedAtMonth: null,
    cashedAtYear: null,
    createdAt: getDateFromToday(15),
    customer: "Ceding",
    description: "Labore laboris eu sit amet velit dolor",
    id: "demo-694e56a0-b198-11ec-b909-0242ac120002",
    isDummy: true,
    owner: "demo",
    remindedAt: [],
    sentAt: getDateFromToday(15),
    updatedAt: getDateFromToday(15),
  },
]

export default dummyBills
