import projectProps from "@localTypes/projectProps"

const dummyProjects: projectProps[] = [
  {
    name: "Click",
    id: "cUwvYMEEMtK6iPhPYxrvi",
    isExpanded: true,
    tasks: [
      {
        description: "Molestiae perspiciatis ipsa",
        id: "gOkP6KzyijfV7ZFcGOz",
        isDummy: true,
        isImportant: false,
        isUrgent: false,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title:
          "Laboriosam mollitia et enim quasi adipisci quia provident illum",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
      {
        description: "",
        id: "gzeuO3fJoPUwsmFt8lu",
        isDummy: true,
        isImportant: true,
        isUrgent: true,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title: "Delectus aut autem",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
      {
        description: "Molestiae perspiciatis ipsa",
        id: "gOkP6KzyijfV7ZFcGO15z",
        isDummy: true,
        isImportant: false,
        isUrgent: false,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title:
          "Laboriosam mollitia et enim quasi adipisci quia provident illum",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
      {
        description: "",
        id: "gzeuO3fJoPUwsmjgF4t8lYcu",
        isDummy: true,
        isImportant: true,
        isUrgent: true,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title: "Delectus aut autem",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
      {
        description: "Molestiae perspiciatis ipsa",
        id: "gOkP6KzyijfV7ZFbfdsdcGOPrz",
        isDummy: true,
        isImportant: false,
        isUrgent: false,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title:
          "Laboriosam mollitia et enim quasi adipisci quia provident illum",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
      {
        description: "",
        id: "gzeuO3fJoPUwsmsfgfgFt8lYcu",
        isDummy: true,
        isImportant: true,
        isUrgent: true,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Click",
        state: "PENDING",
        title: "Delectus aut autem",
        projectId: "cUwvYMEEMtK6iPhPYxrvi",
      },
    ],
    isDummy: true,
    owner: null,
  },
  {
    name: "Awesome Company",
    id: "DD32sHfWKUsfSX-LlL2Xc",
    isExpanded: true,
    tasks: [
      {
        description: "Delectus aut autem",
        id: "b7iOr9g2Z4dKHVTQOJ8fC",
        isDummy: true,
        isImportant: true,
        isUrgent: false,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Awesome Company",
        state: "PENDING",
        title: "Vero rerum temporibus dolor",
        projectId: "DD32sHfWKUsfSX-LlL2Xc",
      },
      {
        description: "Fugiat veniam minus",
        id: "gAaAliSM8pkAFQeH4kulE",
        isDummy: true,
        isImportant: true,
        isUrgent: true,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Awesome Company",
        state: "PENDING",
        title: "Ipsa repellendus fugit nisi",
        projectId: "DD32sHfWKUsfSX-LlL2Xc",
      },
      {
        description: "",
        id: "xkplMI_0y6CFrn_iqErf7",
        isDummy: true,
        isImportant: false,
        isUrgent: true,
        addedAt: 1654668183697,
        startedAt: null,
        finishedAt: null,
        validatedAt: null,
        rejectedAt: null,
        owner: null,
        project: "Awesome Company",
        state: "PENDING",
        title: "Et doloremque nulla",
        projectId: "DD32sHfWKUsfSX-LlL2Xc",
      },
    ],
    isDummy: true,
    owner: null,
  },
]

export default dummyProjects
